# Generated by Django 2.1.7 on 2019-03-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190310_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='unique_key',
            field=models.CharField(max_length=30),
        ),
    ]
