# Generated by Django 2.1.7 on 2019-03-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190311_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='unique_key',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
