# Generated by Django 2.1.7 on 2019-03-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190311_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='unique_username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='unique_key',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
